ROI_CENTER_X 640
ROI_CENTER_Y 512
ROI_WIDTH 1280
ROI_HEIGHT 1024
LINE_MODEL_USE_HOUGH_RANGES 0
LINE_MODEL_REBUILD 0
LINE_MODEL_TYPE 0
LINE_MODEL_EPS 3
END_LINE_ANGLE 0
END_LINE_ANGLE_RANGE  15
SEAM_DETECTOR_MEDIUM_BLUR 0
SEAM_DETECTOR_MEDIUM_BLUR_SIZE 1
LINE_MODEL_EPS2 20
LASER_DETECTOR_TYPE 3
SEAM_DETECTOR_TYPE 1
LINE_MODEL_ITER 2
THRESH_THRESH 15
PEAK_THRESH 30
PEAK1D_THRESH  15
LINE_FEATURE_TYPE 0
USE_LINE_FEATURE 0
LINE_ANGLE 0
LINE_THICKNESS 1
LINE_THRESH 100
ANGLE_BIN_SIZE 2
MIN_GROUP_DISTANCE 2
LINE_DIRECTION 0
DO_EDGE_DETECTION 0
EDGE_LOW_THRESHOLD 60
EDGE_HIGH_THRESHOLD 230
HOUGH_THRESH 50
HOUGH_MINLINELENGTH 90
HOUGH_MAXLINEGAP 20
D2_MEDIAN_LENGTH 17
D2_SMOOTH_LENGTH 15
D2_LENGTH      40
D2_MEDIAN_THRESH  4
